/*
Given an array arr[] of N positive elements. The task is
 to find the Maximum AND Value generated by any pair(arri, arrj)
from the array such that i != j.
Note: AND is bitwise '&' operator.


*/

#include <bits/stdc++.h>
using namespace std;

   int countSetBits(int bit,int arr[],int n){
        int ct=0;
        
        for(int i=0;i<n;i++){
            if((bit&arr[i])==bit){
                ct++;
            }
            
        }
        return ct;
    }
    int maxAND (int arr[], int N)
    {
        // Your code here
        int ans=0;
        for(int i=31;i>=0;i--){
            int count=countSetBits((ans|(1<<i)),arr,N);
            
            if(count>=2){
                ans=(ans|(1<<i));
            }
        }
        return ans;
    }

int main(){



    return 0;
}